### ISSUE TITLE
test-should-exit-code-4.rc fails to compile

### ISSUE THREAD

**Issue by johnvtan** [mfekadu/rc#35]
```
john@machine:~/dev/rc$ ./compiler.rkt programs/test-should-exit-code-4.rc 
ERROR tried to get edges from vertex not in graph
  context...:
   /usr/share/racket/collects/racket/private/map.rkt:25:19: loop
   /home/john/dev/rc/src/allocate-registers.rkt:48:2: helper
   /home/john/dev/rc/src/allocate-registers.rkt:110:0: allocate-registers
   /home/john/dev/rc/compiler.rkt: [running body]
```

**Comment by mfekadu** [comment]
#27 😢 

```racket
> ./run programs/test-should-exit-code-4.rc
select-instructions: select-instructions: bad c0-prog: '(program (complex-op1150 x1149) ((start (seq (assign x1149 2) (seq (assign complex-op1150 (+ x1149 2)) (return complex-op1150))))))
  context...:
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78

  context...:
   /Applications/Racket v7.3/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    do_stuff()
  File "build.py", line 24, in do_stuff
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/test-should-exit-code-4.rc']' returned non-zero exit status 1.
>
```

**Comment by mfekadu** [comment]
weird... cannot reproduce... maybe I was in an old branch?

**```> ./run programs/test-should-exit-code-4.rc```**
**```uncover-live: Bad x86_0 program (program (complex-op1165 x1164) ((label start) (movq (int 2) (var x1164)) (movq (var x1164) (var complex-op1165)) (addq (int 2) (var complex-op1165)) (movq (var complex-op1165) (reg rax)) (jmp conclusion)))```**
```
  context...:
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    do_stuff()
  File "build.py", line 24, in do_stuff
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/test-should-exit-code-4.rc']' returned non-zero exit status 1.
>












```
