### ISSUE TITLE
uniquify

### ISSUE THREAD

**Issue by mfekadu** [mfekadu/rc#36]
https://github.com/mfekadu/rc/pull/34#issuecomment-528965593

Merging into master because ec now handles the `if-should-exit-42.rc` case

```racket
> ./run programs/if-should-exit-42.rc
oh no
  context...:
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    do_stuff()
  File "build.py", line 24, in do_stuff
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/if-should-exit-42.rc']' returned non-zero exit status 1.
```

**Uniquify fails ???**

```racket
> ./run_tests.sh

Running assign-homes tests...
assign homes tests finished

Running ec-tests...
ec tests finished

Running patch instructions tests...
patch instructions tests pass

Running print-x86 tests...
print-x86 tests finished

Running rco tests...
rco tests finished

Running select instructions tests...
select instructions tests finished

Running uncover locals tests...
uncover locals tests finished

Running uncover-live tests...
uncover-live tests finished

Running uniquify tests...
--------------------
FAILURE
name:       check-exn
location:   testing/utilities.rkt:8:27
params:     '(#<procedure:exn:fail?> #<procedure:...iquify-tests.rkt:31:12>)
message:    "No exception raised"
--------------------
uniquify tests finished

Running graph tests...
Graph tests finished running

Running make-interference tests
make interference tests done

Running allocate-registers tests
allocate registers test done

Running typecheck tests
Typecheck tests finished

Running shrink tests
shrink tests finished
>
```

**Comment by mfekadu** [comment]
fixed by 6323e58
